spring.application.name=opp
spring.datasource.url=jdbc:postgresql://localhost:5432/opp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.web=DEBUG

# security code from https://habr.com/ru/articles/784508/
